import { StyleSheet } from 'react-native';

export const taskDetailStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#DFE7DF' },
  bg: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  bgGradient: { flex: 1 },
  content: { paddingHorizontal: 24, paddingBottom: 120 },
  headerWrap: {
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 12,
    paddingRight: 64,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#1F3D2F',
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 2,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
    color: '#1F3D2F',
  },
  section: { marginBottom: 16 },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#1F3D2F',
    marginBottom: 10,
  },
  card: {
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    padding: 16,
    shadowColor: '#1F3D2F',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  taskTitle: { fontSize: 20, lineHeight: 26, fontWeight: '900', color: '#1F3D2F' },
  taskDescription: {
    marginTop: 10,
    fontSize: 14,
    lineHeight: 20,
    color: '#1F3D2F',
    opacity: 0.75,
    fontWeight: '500',
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
  },
  statusTag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#1F3D2F',
    backgroundColor: '#F2F6F2',
  },
  statusTemplate: {
    borderStyle: 'dashed',
    backgroundColor: 'transparent',
  },
  statusPending: {
    borderStyle: 'solid',
    backgroundColor: '#FFF4E5',
    borderColor: '#E2A24B',
  },
  statusInProgress: {
    borderStyle: 'solid',
    backgroundColor: '#E8F2FF',
    borderColor: '#3C78C1',
  },
  statusDone: {
    borderStyle: 'solid',
    borderColor: '#4E8B62',
    backgroundColor: '#A3F7BF',
  },
  statusText: { fontSize: 12, fontWeight: '800', color: '#1F3D2F' },
  metaText: {
    marginTop: 8,
    fontSize: 12,
    color: '#1F3D2F',
    opacity: 0.65,
    fontWeight: '600',
  },
  attributeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ECF0EC',
  },
  attributeRowLast: {
    borderBottomWidth: 0,
  },
  attributeName: { fontSize: 14, color: '#1F3D2F', fontWeight: '700', flex: 1, marginRight: 8 },
  attributeValue: { fontSize: 14, color: '#1F3D2F', fontWeight: '700' },
  checklistItem: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E6ECE6',
    padding: 12,
    marginBottom: 10,
    backgroundColor: '#FAFCFA',
  },
  checklistTop: { flexDirection: 'row', alignItems: 'center' },
  orderBubble: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#E9F3EA',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  orderText: { fontSize: 12, fontWeight: '800', color: '#1F3D2F' },
  checklistName: { flex: 1, fontSize: 14, fontWeight: '700', color: '#1F3D2F' },
  checklistMeta: { marginTop: 8, fontSize: 12, color: '#1F3D2F', opacity: 0.65, fontWeight: '600' },
  checklistStatusRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  checklistStatusTag: {
    paddingVertical: 4,
  },
  editorWrap: {
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E6ECE6',
    paddingTop: 12,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1F3D2F',
    marginBottom: 6,
  },
  input: {
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D5DFD5',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    marginBottom: 10,
    color: '#1F3D2F',
    fontSize: 14,
    fontWeight: '600',
  },
  rowActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 14,
  },
  checklistActionSpacing: {
    marginTop: 14,
  },
  modalSubmitSpacing: {
    marginTop: 14,
  },
  actionHalf: {
    flex: 1,
  },
  primaryButton: {
    height: 42,
    borderRadius: 12,
    backgroundColor: '#1F3D2F',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 13,
  },
  secondaryButton: {
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1F3D2F',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  secondaryButtonText: {
    color: '#1F3D2F',
    fontWeight: '700',
    fontSize: 13,
  },
  completeInfoWrap: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#E6ECE6',
    paddingTop: 10,
  },
  evidenceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  evidenceImage: {
    width: 76,
    height: 76,
    borderRadius: 10,
    backgroundColor: '#E8EFE8',
  },
  selectedImageWrap: {
    position: 'relative',
  },
  removeImageButton: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#7A2E2E',
    justifyContent: 'center',
    alignItems: 'center',
  },
  requestApprovalButton: {
    backgroundColor: '#1F3D2F',
    borderRadius: 999,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  requestApprovalButtonDisabled: {
    backgroundColor: '#CBD8CC',
  },
  requestApprovalText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  requestApprovalTextDisabled: {
    color: '#5F6D63',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(19, 27, 22, 0.45)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 28,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#1F3D2F',
  },
  modalCloseButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ECF2EC',
  },
  modalDescription: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 18,
    color: '#1F3D2F',
    opacity: 0.7,
    marginBottom: 12,
  },
  previewHeader: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  previewTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1F3D2F',
  },
  previewCount: {
    fontSize: 12,
    color: '#1F3D2F',
    opacity: 0.65,
    fontWeight: '700',
  },
  systemTitleText: { marginLeft: 8 },
  systemRow: { marginTop: 10 },
  systemMetaText: { marginTop: 0, marginLeft: 8 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 24 },
  loadingText: { marginTop: 10, color: '#1F3D2F', fontWeight: '600' },
  errorText: { textAlign: 'center', color: '#7A2E2E', fontSize: 14, lineHeight: 20, fontWeight: '600' },
  retryButton: {
    marginTop: 14,
    backgroundColor: '#1F3D2F',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  retryText: { color: '#FFFFFF', fontWeight: '800' },
  emptyText: { fontSize: 13, color: '#1F3D2F', opacity: 0.65, fontWeight: '600' },
});
