import { StyleSheet } from 'react-native';

export const experimentLogDetailStyles = StyleSheet.create({
  // ── Layout ─────────────────────────────────────────────────
  root: { flex: 1, backgroundColor: '#DFE7DF' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', marginTop: 50 },
  bg: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  bgGradient: { flex: 1 },
  content: { paddingHorizontal: 24, paddingBottom: 120 },

  // ── Page header ─────────────────────────────────────────────
  headerWrap: {
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#1F3D2F',
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 2,
  },
  headerTitle: {
    marginLeft: 12,
    marginRight: 12,
    flex: 1,
    textAlign: 'center',
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '900',
    color: '#1F3D2F',
  },

  // ── Action buttons bar ──────────────────────────────────────
  actionRowWrap: {
    marginBottom: 4,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 24,
    paddingVertical: 10,
  },
  btnStart: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#1F3D2F',
    shadowColor: '#1F3D2F',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 3,
    justifyContent: 'center', 
    alignItems: 'center',     
    minHeight: 40,
  },
  btnProtocorm: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#4E8B62',
    shadowColor: '#4E8B62',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 3,
  },
  btnChangeStage: {
    height: 40,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#0e7c40',
    shadowColor: '#1ed378',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 3,
  },
  btnCancelAction: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#DC2626',
    shadowColor: '#DC2626',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 3,
  },
  btnText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },

  // ── Sections & cards ────────────────────────────────────────
  section: { marginBottom: 16 },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#1F3D2F',
    marginBottom: 10,
  },
  card: {
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    padding: 16,
    shadowColor: '#1F3D2F',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  cardTitle: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '900',
    color: '#1F3D2F',
    textAlign: 'center',
    marginBottom: 4,
  },
  cardSubTitle: {
    marginTop: 6,
    marginBottom: 6,
    fontSize: 13,
    color: '#1F3D2F',
    opacity: 0.7,
    fontWeight: '600',
  },

  // ── Info rows ───────────────────────────────────────────────
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#ECF0EC',
    paddingVertical: 10,
    gap: 8,
  },
  infoRowLast: { borderBottomWidth: 0 },
  infoLabel: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    color: '#1F3D2F',
    opacity: 0.65,
    fontWeight: '700',
  },
  infoValue: {
    flex: 1,
    textAlign: 'right',
    fontSize: 14,
    lineHeight: 20,
    color: '#1F3D2F',
    fontWeight: '700',
  },
  scientificName: { fontStyle: 'italic' },
  bodyText: {
    fontSize: 14,
    lineHeight: 22,
    color: '#1F3D2F',
    opacity: 0.85,
    fontWeight: '500',
  },
  bodyTextSpacing: { marginTop: 8 },

  // ── Status badges ───────────────────────────────────────────
  statusTag: {
    marginTop: 10,
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  statusText: { fontSize: 12, fontWeight: '800', color: '#1F3D2F' },
  statusCreated: { backgroundColor: '#E8F2FF', borderColor: '#3C78C1' },
  statusInProgress: { backgroundColor: '#FFF4E5', borderColor: '#E2A24B' },
  statusDone: { backgroundColor: '#A3F7BF', borderColor: '#4E8B62' },
  statusWaiting: { backgroundColor: '#FEF3C7', borderColor: '#D97706' },   // NEW
  statusDestroyed: { backgroundColor: '#FFE5E5', borderColor: '#DC2626' }, // NEW
  statusDefault: { backgroundColor: '#F2F6F2', borderColor: '#1F3D2F' },

  // ── Stage cards ─────────────────────────────────────────────
  stageCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E6ECE6',
    padding: 12,
    marginBottom: 10,
    backgroundColor: '#FAFCFA',
  },
  stageCardPast: { opacity: 0.55 },
  stageCardCurrent: {
    borderColor: '#4E8B62',
    backgroundColor: '#F5FFF7',
    shadowColor: '#4E8B62',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  stageCardUpcoming: { backgroundColor: '#FBFDFC' },
  stageTop: { flexDirection: 'row', alignItems: 'center' },
  stageOrderBubble: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#E9F3EA',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  stageOrderText: { fontSize: 12, fontWeight: '800', color: '#1F3D2F' },
  stageTitleWrap: { flex: 1 },
  stageName: { fontSize: 14, color: '#1F3D2F', fontWeight: '800' },
  stageMeta: {
    marginTop: 2,
    fontSize: 12,
    color: '#1F3D2F',
    opacity: 0.65,
    fontWeight: '600',
  },
  stageCurrentPill: {
    marginLeft: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#A3F7BF',
  },
  stageCurrentPillText: { fontSize: 10, fontWeight: '800', color: '#1F3D2F' },

  // ── isSampleGenerated tag (NEW) ─────────────────────────────
  stageTagRow: { flexDirection: 'row', marginTop: 8 },
  isSampleTag: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
  },
  isSampleTagEnabled: {
    backgroundColor: '#DCFCE7',
    borderColor: '#4E8B62',
  },
  isSampleTagDisabled: {
    backgroundColor: '#F3F4F6',
    borderColor: '#9CA3AF',
  },
  isSampleTagText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1F3D2F',
  },

  // ── Stage expand ────────────────────────────────────────────
  expandAction: {
    marginTop: 10,
    alignSelf: 'flex-end',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#1F3D2F',
  },
  expandActionText: { fontSize: 12, color: '#1F3D2F', fontWeight: '700' },
  stageDivider: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#E6ECE6',
    paddingTop: 10,
  },
  systemTitle: {
    fontSize: 12,
    color: '#1F3D2F',
    opacity: 0.7,
    fontWeight: '800',
    marginBottom: 4,
  },
  systemLine: {
    fontSize: 13,
    lineHeight: 19,
    color: '#1F3D2F',
    fontWeight: '600',
    marginBottom: 2,
  },

  // ── Chemicals & Materials (NEW) ─────────────────────────────
  chemSectionTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1F3D2F',
    marginBottom: 8,
  },
  chemEmpty: {
    fontSize: 13,
    color: '#6B7280',
    fontStyle: 'italic',
    marginBottom: 4,
  },
  chemGroup: { marginBottom: 10 },
  chemCategory: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6B7280',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  chemItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 6,
  },
  chemDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#4E8B62',
    marginTop: 5,
  },
  chemItemName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1F3D2F',
    lineHeight: 18,
  },
  chemItemUnit: {
    fontSize: 11,
    color: '#6B7280',
    marginTop: 1,
  },

  // ── Sample cards ────────────────────────────────────────────
  sampleCard: {
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    padding: 14,
    borderWidth: 1,
    borderColor: '#E6ECE6',
  },
  sampleCardActive: {
    borderColor: '#4E8B62',
    backgroundColor: '#F5FFF7',
  },
  sampleTitle: {
    fontSize: 15,
    lineHeight: 20,
    color: '#1F3D2F',
    fontWeight: '800',
  },
  sampleMeta: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 18,
    color: '#1F3D2F',
    opacity: 0.7,
    fontWeight: '600',
  },
  sampleTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },

  // ── Empty & error states ────────────────────────────────────
  emptyCard: {
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 14,
    borderWidth: 1,
    borderColor: '#E6ECE6',
  },
  emptyText: {
    fontSize: 13,
    lineHeight: 19,
    color: '#1F3D2F',
    opacity: 0.7,
    fontWeight: '600',
  },
  errorCard: {
    marginHorizontal: 24,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2A24B',
  },
  errorTitle: { fontSize: 16, color: '#7A2E2E', fontWeight: '800' },
  errorText: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 18,
    color: '#7A2E2E',
    fontWeight: '600',
  },
  errorActions: { marginTop: 12, flexDirection: 'row', gap: 10 },
  actionHalf: { flex: 1 },
  primaryButton: {
    height: 42,
    borderRadius: 12,
    backgroundColor: '#1F3D2F',
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryButtonText: { fontSize: 13, color: '#FFFFFF', fontWeight: '800' },
  secondaryButton: {
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1F3D2F',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondaryButtonText: { fontSize: 13, color: '#1F3D2F', fontWeight: '700' },

  // ── Modals (NEW) ────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  modalBox: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    gap: 14,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#1F3D2F',
    textAlign: 'center',
  },
  modalLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1F3D2F',
    opacity: 0.8,
  },
  modalInput: {
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 14,
    color: '#1F3D2F',
    fontWeight: '500',
    backgroundColor: '#F9FAFB',
    minHeight: 80,
  },
  modalMessage: {
    fontSize: 14,
    lineHeight: 22,
    color: '#374151',
    fontWeight: '500',
    textAlign: 'center',
  },
  modalSuccessIcon: {
    alignSelf: 'center',
    marginBottom: 4,
  },
  modalFooterRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  modalBtnPrimary: {
    paddingVertical: 13,
    borderRadius: 14,
    backgroundColor: '#1F3D2F',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBtnPrimaryText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  modalBtnSecondary: {
    paddingVertical: 13,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBtnSecondaryText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#374151',
  },
  modalBtnDisabled: {
    opacity: 0.4,
  },

  // ── Protocorm modal extras (NEW) ────────────────────────────
  protocormInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#F0FDF4',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  protocormInfoText: {
    fontSize: 13,
    color: '#1F3D2F',
    fontWeight: '600',
  },
  protocormWarning: {
    fontSize: 12,
    color: '#D97706',
    fontWeight: '700',
  },
});