import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#DFE7DF' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', marginTop: 50 },
  scrollContent: { paddingHorizontal: 24, paddingBottom: 130 },
  listHeaderPadding: { paddingTop: 10, paddingBottom: 16 },
  headerContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', paddingHorizontal: 24, paddingTop: 20, paddingBottom: 16, zIndex: 10 },
  headerTitle: { fontSize: 28, fontWeight: '900', color: '#1F3D2F', lineHeight: 34 },
  headerActions: { flexDirection: 'row', gap: 12 },
  iconButton: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center', shadowColor: '#1F3D2F', shadowOpacity: 0.05, shadowRadius: 10, elevation: 2 },
  floatingCreateButton: {
    position: 'absolute',
    right: 22,
    bottom: Platform.OS === 'ios' ? 122 : 104,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#1F3D2F',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#1F3D2F',
    shadowOpacity: 0.22,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 14,
    elevation: 8,
    zIndex: 20,
  },
  filterContainer: { paddingHorizontal: 24, paddingBottom: 4, alignItems: 'center' },
  chip: { paddingHorizontal: 20, paddingVertical: 10, borderRadius: 999, backgroundColor: 'rgba(255, 255, 255, 0.4)', marginRight: 12 },
  chipActive: { backgroundColor: '#1F3D2F' },
  chipText: { fontSize: 15, fontWeight: '600', color: '#1F3D2F', opacity: 0.7 },
  chipTextActive: { color: '#A3F7BF', opacity: 1 },
  metricsContainer: { flexDirection: 'row', marginBottom: 40, gap: 16 },
  metricCard: { flex: 1, height: 160, borderRadius: 32, padding: 20, justifyContent: 'space-between', shadowColor: '#1F3D2F', shadowOpacity: 0.06, shadowOffset: { width: 0, height: 6 }, shadowRadius: 15, elevation: 3 },
  metricIconWrap: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(31, 61, 47, 0.08)', justifyContent: 'center', alignItems: 'center' },
  metricValue: { fontSize: 26, fontWeight: '800', color: '#1F3D2F', marginTop: 12 },
  metricTitle: { fontSize: 14, fontWeight: '600', color: '#1F3D2F', opacity: 0.8, lineHeight: 20 },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: '#1F3D2F', marginTop: 4, marginBottom: 16 },
  reportCard: { backgroundColor: '#FFFFFF', borderRadius: 28, padding: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', shadowColor: '#1F3D2F', shadowOpacity: 0.03, shadowRadius: 10, elevation: 1 },
  newDot: { position: 'absolute', top: 14, right: 14, width: 8, height: 8, borderRadius: 4, backgroundColor: '#A3F7BF' },
  reportInfo: { flex: 1, paddingRight: 16 },
  reportTitle: { fontSize: 16, fontWeight: '700', color: '#1F3D2F', marginBottom: 6 },
  reportDate: { fontSize: 13, color: '#1F3D2F', opacity: 0.6, fontWeight: '500' },
  statusTag: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999 },
  statusDone: { backgroundColor: '#A3F7BF' },
  statusPending: { backgroundColor: 'transparent', borderWidth: 1.5, borderColor: '#1F3D2F', borderStyle: 'dashed' },
  statusText: { fontSize: 12, fontWeight: '700', color: '#1F3D2F' },
  tabBarContainer: { position: 'absolute', bottom: Platform.OS === 'ios' ? 22 : 18, left: 12, right: 12, height: Platform.OS === 'ios' ? 90 : 70, backgroundColor: '#1F3D2F', borderTopLeftRadius: 30, borderTopRightRadius: 30, borderBottomLeftRadius: 30, borderBottomRightRadius: 30, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', paddingHorizontal: 10, paddingBottom: Platform.OS === 'ios' ? 24 : 6, shadowColor: '#000', shadowOpacity: 0.18, shadowOffset: { width: 0, height: -5 }, shadowRadius: 15, elevation: 12 },
  tabItem: { alignItems: 'center', justifyContent: 'center', width: 70 },
  iconWrapper: { padding: 8, borderRadius: 20 },
  iconWrapperActive: { backgroundColor: 'rgba(163, 247, 191, 0.15)' },
  tabLabel: { fontSize: 10, fontWeight: '600', color: '#8A9E92', marginTop: 4 },
  tabLabelActive: { color: '#A3F7BF', fontWeight: '800' },
});