import { StyleSheet } from 'react-native';

export const batchDetailStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#DFE7DF' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', marginTop: 50 },
  bg: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  bgGradient: { flex: 1 },
  content: { paddingHorizontal: 24, paddingBottom: 120 },
  headerWrap: {
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#1F3D2F',
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 2,
  },
  headerTitle: {
    marginLeft: 12,
    marginRight: 12,
    flex: 1,
    textAlign: 'center',
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
    color: '#1F3D2F',
  },
  section: { marginBottom: 16 },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#1F3D2F',
    marginBottom: 10,
  },
  card: {
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    padding: 16,
    shadowColor: '#1F3D2F',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  cardTitle: {
    fontSize: 21,
    lineHeight: 28,
    fontWeight: '900',
    color: '#1F3D2F',
    textAlign: 'center',
    marginBottom: 8,
  },
  statusBadge: {
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    marginBottom: 10,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1F3D2F',
  },
  badgeReady: { backgroundColor: '#A3F7BF', borderColor: '#4E8B62' },
  badgeInUse: { backgroundColor: '#E8F2FF', borderColor: '#3C78C1' },
  badgeCleaning: { backgroundColor: '#FFF4E5', borderColor: '#E2A24B' },
  badgeMaintenance: { backgroundColor: '#FFEAEA', borderColor: '#D98282' },
  badgeInactive: { backgroundColor: '#F1F2F4', borderColor: '#9EA6B2' },
  badgeDefault: { backgroundColor: '#F2F6F2', borderColor: '#1F3D2F' },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#ECF0EC',
    paddingVertical: 10,
    gap: 8,
  },
  infoRowLast: { borderBottomWidth: 0 },
  infoLabel: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    color: '#1F3D2F',
    opacity: 0.65,
    fontWeight: '700',
  },
  infoValue: {
    flex: 1,
    textAlign: 'right',
    fontSize: 14,
    lineHeight: 20,
    color: '#1F3D2F',
    fontWeight: '700',
  },
  errorCard: {
    marginHorizontal: 24,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2A24B',
  },
  errorTitle: {
    fontSize: 16,
    color: '#7A2E2E',
    fontWeight: '800',
  },
  errorText: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 18,
    color: '#7A2E2E',
    fontWeight: '600',
  },
  errorActions: {
    marginTop: 12,
    flexDirection: 'row',
    gap: 10,
  },
  actionHalf: { flex: 1 },
  primaryButton: {
    height: 42,
    borderRadius: 12,
    backgroundColor: '#1F3D2F',
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryButtonText: {
    fontSize: 13,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  secondaryButton: {
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1F3D2F',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontSize: 13,
    color: '#1F3D2F',
    fontWeight: '700',
  },
});