import { StyleSheet } from 'react-native';

export const createMonitoringLogStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#DFE7DF' },
  bg: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  bgGradient: { flex: 1 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', marginTop: 50 },
  content: { paddingHorizontal: 24, paddingBottom: 120 },
  headerWrap: {
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#1F3D2F',
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 2,
  },
  headerTitle: {
    marginLeft: 12,
    marginRight: 12,
    flex: 1,
    textAlign: 'center',
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
    color: '#1F3D2F',
  },
  section: { marginBottom: 16 },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#1F3D2F',
    marginBottom: 10,
  },
  card: {
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    padding: 16,
    shadowColor: '#1F3D2F',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  statusCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#DCE8DD',
    backgroundColor: '#F6FAF6',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  statusLabel: {
    fontSize: 12,
    lineHeight: 16,
    color: '#1F3D2F',
    opacity: 0.7,
    fontWeight: '700',
  },
  statusValue: {
    marginTop: 2,
    fontSize: 14,
    lineHeight: 20,
    color: '#1F3D2F',
    fontWeight: '900',
  },
  statusSubText: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 16,
    color: '#1F3D2F',
    opacity: 0.65,
    fontWeight: '600',
  },
  rejectionCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2A24B',
    backgroundColor: '#FFF7EA',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  rejectionTitle: {
    fontSize: 13,
    lineHeight: 18,
    color: '#7A2E2E',
    fontWeight: '800',
  },
  rejectionText: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 18,
    color: '#7A2E2E',
    fontWeight: '600',
  },
  inputWrap: {
    marginBottom: 12,
  },
  label: {
    fontSize: 13,
    lineHeight: 18,
    color: '#1F3D2F',
    opacity: 0.75,
    fontWeight: '700',
    marginBottom: 6,
  },
  requiredStar: {
    color: '#B33A3A',
    fontWeight: '900',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E2EAE2',
    borderRadius: 14,
    backgroundColor: '#FAFCFA',
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#1F3D2F',
    fontWeight: '600',
  },
  textarea: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  readonlyInput: {
    backgroundColor: '#F6FAF6',
    color: '#4F6658',
  },
  readonlyNoteCard: {
    borderWidth: 1,
    borderColor: '#DCE8DD',
    borderRadius: 14,
    backgroundColor: '#F6FAF6',
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: 'flex-start',
  },
  readonlyNoteText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#4F6658',
    fontWeight: '600',
  },
  selectButton: {
    borderWidth: 1,
    borderColor: '#E2EAE2',
    borderRadius: 14,
    backgroundColor: '#FAFCFA',
    paddingHorizontal: 12,
    minHeight: 44,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  selectButtonDisabled: {
    opacity: 0.5,
  },
  selectText: {
    flex: 1,
    fontSize: 14,
    color: '#1F3D2F',
    fontWeight: '600',
  },
  selectPlaceholder: {
    color: '#6F857A',
    fontWeight: '500',
  },
  helperText: {
    marginTop: 6,
    fontSize: 12,
    lineHeight: 16,
    color: '#1F3D2F',
    opacity: 0.65,
    fontWeight: '600',
  },
  requirementCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E6ECE6',
    backgroundColor: '#FAFCFA',
    padding: 12,
    marginBottom: 8,
  },
  requirementName: {
    fontSize: 14,
    lineHeight: 20,
    color: '#1F3D2F',
    fontWeight: '800',
  },
  requirementMeta: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 18,
    color: '#1F3D2F',
    opacity: 0.72,
    fontWeight: '600',
  },
  requirementInputWrap: {
    marginTop: 10,
  },
  switchRow: {
    borderWidth: 1,
    borderColor: '#E2EAE2',
    borderRadius: 14,
    backgroundColor: '#FAFCFA',
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  switchLabelWrap: {
    flex: 1,
  },
  switchTitle: {
    fontSize: 14,
    lineHeight: 20,
    color: '#1F3D2F',
    fontWeight: '800',
  },
  switchDesc: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 16,
    color: '#1F3D2F',
    opacity: 0.68,
    fontWeight: '600',
  },
  submitButton: {
    marginTop: 14,
    borderRadius: 14,
    backgroundColor: '#1F3D2F',
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  errorCard: {
    marginHorizontal: 24,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2A24B',
  },
  errorTitle: {
    fontSize: 16,
    color: '#7A2E2E',
    fontWeight: '800',
  },
  errorText: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 18,
    color: '#7A2E2E',
    fontWeight: '600',
  },
  errorActions: {
    marginTop: 12,
    flexDirection: 'row',
    gap: 10,
  },
  actionHalf: { flex: 1 },
  secondaryButton: {
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1F3D2F',
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1F3D2F',
  },
  primaryButton: {
    height: 42,
    borderRadius: 12,
    backgroundColor: '#1F3D2F',
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  actionRow: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  analysisRow: {
    flexDirection: 'row',
    gap: 10,
  },
  analysisPreviewWrap: {
    marginTop: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E6ECE6',
    backgroundColor: '#FAFCFA',
    padding: 10,
  },
  analysisPreviewImage: {
    width: '100%',
    height: 180,
    borderRadius: 10,
    backgroundColor: '#E8EFE8',
  },
  analysisPreviewText: {
    marginTop: 8,
    fontSize: 12,
    lineHeight: 16,
    color: '#1F3D2F',
    opacity: 0.7,
    fontWeight: '600',
  },
  analysisResultCard: {
    marginTop: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#4E8B62',
    backgroundColor: '#F5FFF7',
    padding: 10,
  },
  analysisResultTitle: {
    fontSize: 13,
    lineHeight: 18,
    color: '#1F3D2F',
    fontWeight: '800',
  },
  analysisResultText: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 16,
    color: '#1F3D2F',
    opacity: 0.75,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(13,22,18,0.45)',
    justifyContent: 'flex-end',
  },
  pickerSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    maxHeight: '72%',
    paddingBottom: 20,
  },
  pickerHeader: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2EE',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pickerTitle: {
    fontSize: 16,
    color: '#1F3D2F',
    fontWeight: '800',
  },
  closeText: {
    fontSize: 13,
    color: '#1F3D2F',
    fontWeight: '700',
    opacity: 0.75,
  },
  optionRow: {
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2EE',
  },
  optionRowActive: {
    backgroundColor: '#F3FBF5',
  },
  optionText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#1F3D2F',
    fontWeight: '700',
  },
  optionEmpty: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    fontSize: 13,
    color: '#1F3D2F',
    opacity: 0.65,
    fontWeight: '600',
  },
});
